--[[
    Language Localization: enUS
    Translated by: name <email address>
]]

WIM.AddLocale("enUS", {
    ["WIM (WoW Instant Messenger)"] = true,
    ["_Description"] = "WIM is an addon that brings a familiar feel to communicating through chat in The World of Warcraft. On this screen you will be able to customize WIM to tailor it to your needs. If you have any questions, comments or suggestions please go to http://www.WIMAddon.com.",

    ["_DemoText"] = "This is a demonstration window and is not fully functional. Place this window in the location where you want all other windows to spawn. When finished, you may close this window and your settings will be saved.",

    ["Yes"] = true,
    ["No"] = true,
    ["None"] = true,
    ["<Right-Click>"] = true,
    ["<Left-Click>"] = true,
    ["OK"] = true,
    ["Cancel"] = true,
    ["Unknown"] = true,
    ["Click to update..."] = true,
    ["Usage"] = true,
    
    ["state_resting"] = "Resting",
    ["state_combat"] = "Combat",
    ["state_pvp"] = "PVP",
    ["state_arena"] = "Arena",
    ["state_party"] = "Party Instance",
    ["state_raid"] = "Raid Instance",
    ["state_other"] = "Normal (Other)",
    
    ["<Shift-Click> to close window."] = true,
    
    ["A new version of WIM is available!\nYou can download the latest version by going to:\n\n http://www.wimaddon.com"] = true,
    
    ["Options"] = true,
    
    ["Icon Position"] = true,
    ["Font Size"] = true,
    ["Window Scale (Percent)"] = true,
    ["Transparency (Percent)"] = true,
    ["Window Width"] = true,
    ["Window Height"] = true,
    ["(Limited by shortcut bar)"] = true,
    ["ERROR"] = true,
    ["Invalid Name!"] = true,
    ["Name is already used!"] = true,
    ["Invalid Alias!"] = true,
    ["Invalid Keyword/Phrase!"] = true,
    ["Keyword/Phrase is already used!"] = true,
    
    ["Day"] = true,
    ["Week"] = true,
    ["Month"] = true,
    ["Drag to set default spawn/position for message windows."] = true,
    ["Up"] = true,
    ["Down"] = true,
    ["Left"] = true,
    ["Right"] = true,
    ["Ignore"] = true,
    ["Block"] = true,
    ["Enable WIM"] = true,
    
    ["Auto Close Friends after:"] = true,
    ["Auto Close Non-Friends after:"] = true,
    
    ["Display"] = true,
    ["Incoming Messages"] = true,
    ["Outgoing Messages"] = true,
    ["System Messages"] = true,
    ["Error Messages"] = true,
    ["Web URLs"] = true,
    ["Enable"] = true,
    ["Disable"] = true,
    ["Enabled"] = true,
    ["Disabled"] = true,
    ["Display character information."] = true,
    ["Display time stamps"] = true,
    ["This setting limits the\nwindow's minimum height."] = true,
    ["Requires /who querying."] = true,
    ["Enable window fading effects."] = true,
    ["Enable window animations."] = true,
    
    ["Display minimap icon."] = true,
    
    ["General"] = true,
    ["History"] = true,
    ["Filters"] = true,
    ["Plugins"] = true,
    
    ["Auto focus when window is shown."] = true,
    ["Preserve focus after sending messages."] = true,
    ["Display tooltips."] = true,
    ["Show window when sending a message."] = true,
    ["Show window when message has been received."] = true,
    ["Supress messages from default chat frame."] = true,
    ["Play sound when message is received."] = true,
    ["Play sound when message is sent."] = true,
    ["Sort alphabetically."] = true,
    ["Use <Escape> to close windows."] = true,
    ["Windows will close when opening the world map."] = true,
    ["Intercept slash commands."] = true,
    ["Ignore arrow keys while typing."] = true,
    ["Requires using <Alt> to navigate text."] = true,
    ["Display emoticons."] = true,
    ["Display URLs as item links."] = true,
    ["Display floating item links."] = true,
    
    ["Cascade windows."] = true,
    ["Direction:"] = true,
    ["Tabs"] = true,
    ["Sort tabs by:"] = true,
    ["Alphabetical"] = true,
    ["Recent Activity"] = true,
    ["Keep windows on top of your UI."] = true,
    
    -- Class Names --
    ["Druid"] = true,
    ["Hunter"] = true,
    ["Mage"] = true,
    ["Paladin"] = true,
    ["Priest"] = true,
    ["Rogue"] = true,
    ["Shaman"] = true,
    ["Warlock"] = true,
    ["Warrior"] = true,
    ["Death Knight"] = true,
    
    -- Female Class Names --
    ["DruidF"] = "Druid",
    ["HunterF"] = "Hunter",
    ["MageF"] = "Mage",
    ["PaladinF"] = "Paladin",
    ["PriestF"] = "Priest",
    ["RogueF"] = "Rogue",
    ["ShamanF"] = "Shaman",
    ["WarlockF"] = "Warlock",
    ["WarriorF"] = "Warrior",
    ["Death KnightF"] = "Death Knight",
    
    ["Game Master"] = true,
});