--[[
    Language Localization: zhCN
    Translated by: MouJiaoZi  moujiaozi@outlook.com
]]

WIM.AddLocale("zhCN", {
    ["WIM (WoW Instant Messenger)"] = "WIM 魔兽即时通讯",
    ["_Description"] = "WIM是一款在魔兽世界中提供熟悉的即时聊天风格的悄悄话插件，在本界面中你可以进行自定义以适应你的需求。",

    ["_DemoText"] = "这是一个仅用于预览的窗口示例，调整此窗口的位置将调整真正的对话窗口打开的位置，将其移动到合适的位置后通过右上角关闭窗口，窗口的位置设置将自动保存。",

    ["_DateFormat"] = "%Y/%m/%d",

    ["Yes"] = "是",
    ["No"] = "否",
    ["None"] = "无",
    ["<Right-Click>"] = "<右键>",
    ["<Left-Click>"] = "<左键>",
    ["OK"] = "确认",
    ["Cancel"] = "取消",
    ["Unknown"] = "未知",
    ["Click to update..."] = "点击更新...",
    ["Usage"] = "使用方法",

    ["state_resting"] = "休息",
    ["state_combat"] = "战斗中",
    ["state_pvp"] = "PVP",
    ["state_arena"] = "竞技场",
    ["state_party"] = "在小队中",
    ["state_raid"] = "在团队中",
    ["state_other"] = "其他情况",

    ["<Shift-Click> to close window."] = "按住Shift点击关闭窗口。",

    ["A new version of WIM is available!\nYou can download the latest version from curse"] = "WIM的新版本已经可用！\n你可以在Curse中进行更新。",

    ["Options"] = "选项",

    ["Icon Position"] = "图标位置",
    ["Font Size"] = "字体大小",
    ["Window Scale (Percent)"] = "窗口缩放（百分比）",
    ["Transparency (Percent)"] = "透明度（百分比）",
    ["Window Width"] = "窗口宽度",
    ["Window Height"] = "窗口高度",
    ["(Limited by shortcut bar)"] = "（受到快捷栏限制）",
    ["ERROR"] = "错误",
    ["Invalid Name!"] = "无效的名字！",
    ["Name is already used!"] = "名字已被使用！",
    ["Invalid Alias!"] = "无效的别名！",
    ["Invalid Keyword/Phrase!"] = "无效的关键词/短语！",
    ["Keyword/Phrase is already used!"] = "关键词/短语已被使用！",

    ["Day"] = "天",
    ["Week"] = "周",
    ["Month"] = "月",
    ["Drag to set default spawn/position for message windows."] = "拖动以设置聊天窗口的默认打开位置。",
    ["Up"] = "上",
    ["Down"] = "下",
    ["Left"] = "左",
    ["Right"] = "右",
    ["Ignore"] = "忽略",
    ["Block"] = "屏蔽",
    ["Enable WIM"] = "启动WIM",

    ["Auto Close Friends after:"] = "在一定时间后自动关闭好友的对话：",
    ["Auto Close Non-Friends after:"] = "在一定时间后自动关闭非好友的对话：",

    ["Display"] = "显示",
    ["Incoming Messages"] = "收到的消息",
    ["Outgoing Messages"] = "发出的消息",
    ["System Messages"] = "系统消息",
    ["Error Messages"] = "错误消息",
    ["Web URLs"] = "网址",
    ["Enable"] = "启用",
    ["Disable"] = "禁用",
    ["Enabled"] = "启用",
    ["Disabled"] = "禁用",
    ["Display character information."] = "显示角色信息。",
    ["Display time stamps"] = "显示时间",
    ["This setting limits the\nwindow's minimum height."] = "本设置限制了\n窗口的最低高度。",
    ["Requires /who querying."] = "需要使用/who查询。",
    ["Enable window fading effects."] = "开启窗口渐隐效果。",
    ["Enable window animations."] = "开启窗口动画效果。",

    ["Display minimap icon."] = "显示小地图图标。",

    ["General"] = "一般",
    ["History"] = "历史记录",
    ["Filters"] = "过滤",
    ["Plugins"] = "插件",

    ["Auto focus when window is shown."] = "窗口出现时自动进入输入文字状态。",
    ["Preserve focus after sending messages."] = "发出信息后保留文字输入状态。",
    ["Display tooltips."] = "显示鼠标提示。",
    ["Show window when sending a message."] = "发送消息时打开窗口。",
    ["Show window when message has been received."] = "收到消息时打开窗口。",
    ["Supress messages from default chat frame."] = "禁止来自默认聊天框的消息。",
    ["Play sound when message is received."] = "收到消息时播放音效。",
    ["Play sound when message is sent."] = "发出消息时播放音效。",
    ["Sort alphabetically."] = "按字母顺序排序。",
    ["Use <Escape> to close windows."] = "使用<ESC>关闭窗口。",
    ["Windows will close when opening the world map."] = "打开大地图后关闭窗口。",
    ["Intercept slash commands."] = "阻止“/xxx”命令。",
    ["Ignore arrow keys while typing."] = "输入信息时忽略方向键。",
    ["Requires using <Alt> to navigate text."] = "需要按住<Alt>移动光标位置。",
    ["Display emoticons."] = "显示表情。",
    ["Display URLs as item links."] = "以物品链接形式显示网址。",
    ["Display floating item links."] = "显示浮动物品链接。",

    ["Cascade windows."] = "层叠窗口。",
    ["Direction:"] = "方向：",
    ["Tabs"] = "选项卡",
    ["Sort tabs by:"] = "选项卡排序方法：",
    ["Alphabetical"] = "ID首字母",
    ["Recent Activity"] = "最后一条消息时间",
    ["Keep windows on top of your UI."] = "保持窗口处于界面最上层。",

    ["Enable/Disable addon messages."] = "启用/禁用插件消息。",

    -- Class Names --
    ["Druid"] = LOCALIZED_CLASS_NAMES_MALE.DRUID,
    ["Hunter"] = LOCALIZED_CLASS_NAMES_MALE.HUNTER,
    ["Mage"] = LOCALIZED_CLASS_NAMES_MALE.MAGE,
    ["Paladin"] = LOCALIZED_CLASS_NAMES_MALE.PALADIN,
    ["Priest"] = LOCALIZED_CLASS_NAMES_MALE.PRIEST,
    ["Rogue"] = LOCALIZED_CLASS_NAMES_MALE.ROGUE,
    ["Shaman"] = LOCALIZED_CLASS_NAMES_MALE.SHAMAN,
    ["Warlock"] = LOCALIZED_CLASS_NAMES_MALE.WARLOCK,
    ["Warrior"] = LOCALIZED_CLASS_NAMES_MALE.WARRIOR,
    ["Death Knight"] = LOCALIZED_CLASS_NAMES_MALE.DEATHKNIGHT,
    ["Monk"] = LOCALIZED_CLASS_NAMES_MALE.MONK,
    ["Demon Hunter"] = LOCALIZED_CLASS_NAMES_MALE.DEMONHUNTER,

    -- Female Class Names --
    ["DruidF"] = LOCALIZED_CLASS_NAMES_FEMALE.DRUID,
    ["HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.HUNTER,
    ["MageF"] = LOCALIZED_CLASS_NAMES_FEMALE.MAGE,
    ["PaladinF"] = LOCALIZED_CLASS_NAMES_FEMALE.PALADIN,
    ["PriestF"] = LOCALIZED_CLASS_NAMES_FEMALE.PRIEST,
    ["RogueF"] = LOCALIZED_CLASS_NAMES_FEMALE.ROGUE,
    ["ShamanF"] = LOCALIZED_CLASS_NAMES_FEMALE.SHAMAN,
    ["WarlockF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARLOCK,
    ["WarriorF"] = LOCALIZED_CLASS_NAMES_FEMALE.WARRIOR,
    ["Death KnightF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEATHKNIGHT,
    ["MonkF"] = LOCALIZED_CLASS_NAMES_FEMALE.MONK,
    ["Demon HunterF"] = LOCALIZED_CLASS_NAMES_FEMALE.DEMONHUNTER,

    ["Game Master"] = "GM",

    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = "切换WIM开/关。",
    ["Toggle Debugging Mode 'On' and 'Off'."] = "切换Debug模式开/关。",
    ["WIM is currently running. To access WIM's wide array of options type:"] = "WIM正在运行，要设置WIM，请输入：",

    -- Filters.lua --
    ["Whispers Sent by Addons"] = "由插件发送的悄悄话",
    ["WhisperSelect Part 1"] = "悄悄话选择区1",
    ["Example Spam Blocker"] = "骚扰屏蔽示例",
    ["WhisperSelect Part 2"] = "悄悄话选择区2",
    ["Filter Name"] = "过滤器名称",
    ["Filter By"] = "过滤",
    ["Pattern"] = "方案",
    ["User Type"] = "用户类型",
    ["Level"] = "等级",
    ["Friends"] = "好友",
    ["Guild Members"] = "公会成员",
    ["Party Members"] = "小队成员",
    ["Raid Members"] = "团队成员",
    ["Cross-Realm"] = "其他服务器",
    ["Everyone"] = "所有人",
    ["User must be at least level:"] = "玩家最低等级：",
    ["Apply to messages received."] = "应用至收到的信息。",
    ["Apply to messages sent."] = "应用到发送的信息。",
    ["Action to Perform:"] = "操作：",
    ["Allow"] = "允许",
    ["Ignore"] = "忽略",
    ["Blocked"] = "屏蔽",
    ["Save"] = "保存",
    ["Cancel"] = "取消",
    ["Edit Filter"] = "修改过滤器",
    ["Add Filter"] = "添加过滤器",

    -- History.lua --
    ["WIM History Button"] = "WIM历史按钮",
    ["Clicking the %s button on the message window will show that user's history in WIM's History Viewer."] = "点击在聊天窗口的“%s”按钮将在WIM消息历史浏览器中显示该角色的历史消息。",
    ["Click to view message history."] = "点击查看历史消息。",
    ["WIM pruned %d |4message:messages; from your history."] = "WIM从历史记录中显示了 %d |4message:messages; 消息。",
    ["History Viewer"] = "消息历史浏览器",
    ["Filters"] = "过滤器",
    ["Are you sure you want to delete all history saved for %s on %s?"] = "你确定要删除 %s 的 %s 所有历史记录吗？",
    ["Search resulted in %d |4message:messages;."] = "找到 %d |4message:messages; 消息。",
    ["No results found!"] = "没有任何结果！",
    ["Search"] = "搜索",
    ["Show All"] = "显示全部",
    ["Loading History"] = "正在载入历史记录",
    ["Chat View"] = "查看聊天",
    ["Text View"] = "查看文本",
    ["WIM History Viewer can be accessed any time by typing:"] = "WIM消息历史浏览器可以通过输入以下命令打开：",
    ["WIM History Viewer"] = "WIM消息历史浏览器",
    ["Display history viewer."] = "打开消息历史浏览器。",

    -- ldb.lua --
    ["No New Messages"] = "没有新消息",

    -- Menu.lua --
    ["Whispers"] = "悄悄话",
    ["Chat"] = "聊天",

    -- Negotiate.lua --
    ["WIM Update Available!"] = "WIM的新版本已经可用！",
    ["There is a newer version of WIM available for download. You can download it at %s."] = "WIM的新版本已经可用，你可以在%s下载。",

    -- ShortcutBar.lua --
    ["Player Location"] = "玩家地区",
    ["Unknown"] = "未知",
    ["Click to update..."] = "点击更新...",
    ["Coordinates"] = true,
    ["Invite to Party"] = "邀请",
    ["Add Friend"] = "添加好友",
    ["Ignore User"] = "屏蔽",
    ["Are you sure you want to\nignore %s?"] = "确定要屏蔽 %s 吗？",
    ["Right-Click for profile links..."] = "右键查看英雄榜链接...",
	["Profile Links"] = "英雄榜链接",
	["Location"] = "地区",
	["Game"] = "游戏",
	["Realm"] = "服务器",
	["Character"] = "角色",

    -- Tutorials.lua --
    ["Display WIM tips"] = "显示WIM提示",

    -- W2W.lua --
    ["%s is typing..."] = "%s 正在输入中...",
    ["W2W Profile"] = "W2W配置",
    ["Talent Spec"] = "查看天赋",

    -- WhisperEngine.lua --
    ["Whisper Received!"] = "新悄悄话！",
    ["You received a whisper which was hidden due to your current activity. You can change how whispers behave in WIM's options by typing"] = "由于你的当前状态，收到的悄悄话已经被隐藏，要改变设置，请在聊天框中输入",
    ["Recently Sent Messages"] = "最近发出的消息",

    -- Clear.lua --
    ["You are about to clear all of WIM's history!"] = "你正在删除所有WIM的消息历史！",
    ["This action will reload your user interface."] = "这个操作将重载你的用户界面（/reload /rl）",
    ["Do you want to continue?"] = "你确定要继续吗？",
    ["You are about to restore WIM's filters to it's default settings!"] = "你正在重置WIM的过滤器设置！",
    ["Usage"] = "使用方法：",
    ["Clear various WIM data."] = "清除大量WIM数据。",

    -- SlashHandler.lua --
    ["WIM Slash Commands"] = "WIM斜杠（/）命令",
    ["To see a list of available WIM slash commands type:"] = "要查看所有可用的斜杠（/）命令，请输入：",
    ["Display available slash commands."] = "显示可用的斜杠（/）命令。",
    ["Reload User Interface."] = "重新加载用户界面（/reload /rl）",

    -- TabHandler.lua --
    ["Manipulating Tabs"] = "操纵选项卡",
    ["You can <Shift-Click> a tab and drag it out into it's own window."] = "你可以通过Shift+点击一个选项卡并拖动它到目标窗口中。",

    -- WindowHandler.lua --
    ["Window Resized!"] = "已改变窗口大小！",
    ["If you want all windows to be this size, you can set the default window size within WIM's options."] = "如果你想让所有窗口都以这个大小出现，你可以在WIM的设置中进行设置。",
    ["Creating Tab Groups"] = "创建选项卡组",
    ["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = "你可以通过Shift+点击一个选项卡并将其拖动到其他选项卡上来组合它们。",
    ["Resizing Windows"] = "改变窗口大小",
    ["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = "你可以按住Shift并拖动窗口右下角来调整窗口的大小。",
    ["Demo Window"] = "示例窗口",
    ["<Shift-Click> to close window."] = "Shift+点击以关闭窗口。",
    ["Message Window Hidden"] = "已隐藏聊天窗口",
    ["WIM's message window has been hidden to WIM's Minimap Icon. If you want to end a conversation, you may do so by <Shift-Clicking> the close button."] = "一个聊天窗口已经隐藏至WIM小地图按钮中，如果你想完全关闭它，请按住Shift点击关闭按钮。",
    ["Default"] = "默认",
    ["%s is Away From Keyboard: %s"] = "%s 正处于离开状态: %s",
    ["%s does not wish to be disturbed: %s"] = "%s 不愿被打扰: %s",
    ["Right-Mouse Click!"] = "右键点击！",
    ["There might be useful tools hidden under the message box. Right-Click to see them!"] = "在消息窗口下隐藏了有用的工具，右键点击来查看它们！",


    -- Options.lua --
    ["Display WIM's options."] = true,
    ["Resetting WIM will clear all of your settings!"] = true,
    ["Reset all options to default."] = true,

    -- CoreOptions --
    ["Created By:"] = true,
    ["Special Thanks:"] = true,
    ["Welcome!"] = true,
    ["Enable WIM"] = true,
    ["Display Minimap Icon"] = true,
    ["<Right-Click> to show unread messages."] = true,
    ["Display Tutorials"] = true,
    ["Reset Tutorials"] = true,
    ["Credits"] = true,
    ["This is a long message which contains both emoticons and urls 8)."] = true,
    ["Message Formatting"] = true,
    ["Manipulate how WIM displays messages."] = true,
    ["Preview"] = true,
    ["Display Time Stamps"] = true,
    ["Display Emoticons"] = true,
    ["Display URLs as Links"] = true,
	["Indent long messages."] = true,
	["Bracket names."] = true,
    ["Window Behavior"] = true,
    ["You can control how windows behave while you are in different situations."] = true,
    ["Intercept Slash Commands"] = true,
	["Obey autofocus rules when opening frames via the menu. (autofocus if unchecked)"] = true,
    ["Use the same rules for all states."] = true,
    ["Behaviors for state:"] = true,
    ["Pop-Up window when message is sent."] = true,
    ["Pop-Up window when message is received."] = true,
    ["Auto focus a window when it is shown."] = true,
    ["Keep focus on window after sending a message."] = true,
    ["Suppress messages from the default chat frame."] = true,
    ["Window Settings"] = true,
    ["Some settings may be limited by certain skins."] = true,
    ["Default Width"] = true,
    ["Default Height"] = true,
    ["Window Scale"] = true,
    ["Window Alpha"] = true,
    ["Set Window Spawn Location"] = true,
    ["Up"] = true,
    ["Down"] = true,
    ["Left"] = true,
    ["Right"] = true,
    ["Cascade overlapping windows."] = true,
    ["Ignore arrow keys in message box."] = true,
    ["Allow <ESC> to hide windows."] = true,
    ["Display Settings"] = true,
    ["Configure general window display settings."] = true,
    ["Window Skin:"] = true,
    ["Version"] = true,
    ["Color: System Messages"] = true,
    ["Color: Error Messages"] = true,
    ["Color: URL - Web Addresses"] = true,
    ["Color: History Messages Sent"] = true,
    ["Color: History Messages Received"] = true,
    ["Use colors suggested by skin."] = true,
    ["Enable window fading effects."] = true,
    ["Enable window animation effects."] = true,
    ["Display item links when hovering over them."] = true,
    ["Fonts"] = true,
    ["Configure the fonts used in WIM's message windows."] = true,
    ["Font Outline"] = true,
    ["Thin"] = true,
    ["Thick"] = true,
    ["Use font suggested by skin."] = true,
    ["Chat Font Size"] = true,
    ["Configure general display settings when dealing with whispers."] = true,
    ["Color: Messages Sent"] = true,
    ["Color: Messages Received"] = true,
    ["Use colors suggested by skin."] = true,
    ["Display user class icons and details."] = true,
    ["Requires who lookups."] = true,
    ["Display Shortcut Bar"] = true,
    ["Allow"] = true,
    ["Ignore"] = true,
    ["Block"] = true,
    ["Filtering"] = true,
    ["Filtering allows you to control which messages are handled as well as how they are handlef by WIM."] = true,
    ["Enable Filtering"] = true,
    ["Protected"] = true,
    ["Action:"] = true,
    ["Occurrences:"] = true,
    ["Delete Filter"] = true,
    ["History"] = true,
    ["WIM can store conversations to be viewed at a later time."] = true,
    ["Enable History"] = true,
    ["Messages"] = true,
    ["Preview history inside message windows."] = true,
    ["Record Whispers"] = true,
    ["Record Friends"] = true,
    ["Record Guild"] = true,
    ["Record Everyone"] = true,
    ["Record Chat"] = true,
    ["Maintenance"] = true,
    ["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = true,
    ["Save a maximum number of messages per person."] = true,
    ["%d |4Week:Weeks;"] = true,
    ["Automatically delete old messages."] = true,
    ["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = true,
    ["Enable WIM-2-WIM"] = true,
    ["Privacy"] = true,
    ["Restrict the data that is shared."] = true,
    ["Allow others to see me typing."] = true,
    ["Allow others to see my location."] = true,
    ["Main"] = true,
    ["General"] = true,
    ["User Level"] = true,
    ["Windows will also be hidden when frames such as the world map are shown."] = true,
    ["Sounds"] = true,
    ["Configure various sound events and how they are triggered."] = true,
    ["Play sound when a whisper is received."] = true,
	["Play special sound for friends."] = true,
	["Play special sound for battle.net friends."] = true,
    ["Play special sound for guild members."] = true,
    ["Play sound when a whisper is sent."] = true,
    ["Allow others to see my talent spec."] = true,
    ["Window Strata:"] = true,
    ["Unlock from Minimap"] = true,
	["Press <Tab> to advance to next tell target."] = true,
	["Force sounds when game sound is disabled."] = true,
    ["Colorize names."] = true,
    ["Clamp window to screen."] = true,
	["Group with whisper windows."] = true,
	["Color: BNet Messages Sent"] = true,
	["Color: BNet Messages Received"] = true,

    -- TabManagement.lua --
    ["Tab Management"] = true,
    ["Automatically manage your open windows and place them into appropriate tab groups."] = true,
    ["Automatically group whispers."] = true,
    ["Place friends in their own group."] = true,
	["Place guild members in their own group."] = true,
	["Automatically group chat windows."] = true,
    ["Does not apply to windows already opened."] = true,


    -- Talent Specs --
    ["Affliction"] = true,
    ["Arcane"] = true,
    ["Arms"] = true,
    ["Assassination"] = true,
    ["Balance"] = true,
    ["Beast Mastery"] = true,
    ["Blood"] = true,
    ["Brewmaster"] = true,
    ["Combat"] = true,
    ["Demonology"] = true,
    ["Destruction"] = true,
    ["Discipline"] = true,
    ["Elemental"] = true,
    ["Enhancement"] = true,
    ["Feral Combat"] = true,
    ["Fire"] = true,
    ["Frost"] = true,
    ["Fury"] = true,
    ["Guardian"] = true,
    ["Holy"] = true,
    ["Hybrid"] = true,
    ["Marksmanship"] = true,
    ["Mistweaver"] = true,
    ["Protection"] = true,
    ["Restoration"] = true,
    ["Retribution"] = true,
    ["Shadow"] = true,
    ["Subtlety"] = true,
    ["Survival"] = true,
    ["Unholy"] = true,
    ["Windwalker"] = true,
    ["Havok"] = true,
    ["Vengeance"] = true,

    -- ChangeLog.lua --
    ["Change Log"] = true,
    ["View WIM's change log."] = true,
    ["Available For Download!"] = true,

    -- Filters.lua --
    ["Show Alert"] = true,
    ["WIM has blocked a message from %s."] = true,
    ["View Blocked Message"] = true,
    ["Blocked Message"] = true,

    -- MinimapIcon.lua
    ["Show Unread Messages"] = true,
    ["Show All Windows"] = true,
    ["Hide All Windows"] = true,

    --Emoticons.lua
    ["Also"] = true,
    ["More"] = true,
    ["Emoticons"] = true,

    --Expose.lua
    ["Your conversations have been hidden in order to clear your screen while in combat. To disable this feature type"] = true,
    ["Expose"] = true,
    ["Expose is a Mac OS X inspired feature which enables you to quickly clear your screen of windows and then restore them back to their original position."] = true,
	["Auto hide/restore windows during combat."] = true,
	["Delay if I am typing a message."] = true,
    ["Border Size"] = true,
    ["Only while in an instance."] = true,
    ["Show Border"] = true,
    ["Animation Direction:"] = true,

    --ChatEngine.lua
    ["WIM will manage this chat type within its own message windows."] = true,
    ["Show Minimap Alerts"] = true,
    ["Never pop-up on my screen."] = true,
	["Never suppress messages."] = true,
	["Include emotes."] = true,
    ["Have WIM monitor this channel."] = true,
    ["Never Pop"] = true,
    ["Never have this window pop-up on my screen."] = true,
    ["Never Supress"] = true,
    ["Never suppress messages from the default chat frame."] = true,
    ["Show unread message alert on minimap."] = true,
    ["No History"] = true,
    ["Do not record history for this channel."] = true,
    ["World Chat"] = true,
    ["Custom Chat"] = true,
    ["Chat"] = true,
    ["Play special sound for %s."] = true,
    ["Play sound when a message is received."] = true,
    ["Play sound when a message is sent."] = true,
    ["Do not play sounds for this channel."] = true,
    ["No Sound"] = true,
    ["Sensitivity"] = true,
    ["Enable WorldFrame Click Detection."] = true,
    ["The UI must be reloaded in order to disable this module fully. Reload UI now?"] = true,

    --OffScreenTracker.lua
    ["WIM Window Off Screen"] = true,
    ["Click to reposition."] = true,

    --Misc
    ["WIM has detected that you are playing on a private server. Some servers can not process ChatAddonMessages. Would you like to enable them anyway?"] = true,

});
